apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mc18hw73d-nodejs
  janus-idp.io/tekton: mc18hw73d-nodejs
  backstage.io/kubernetes-id: mc18hw73d-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mc18hw73d-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
